export const DEFAULT_SVG_SIZE = 300;

export const DEFAULT_LINE_WIDTH = 1;

export const DEFAULT_LINE_COLOR = 'black';

export const DEFAULT_LINE = [DEFAULT_SVG_SIZE/2, 0, DEFAULT_SVG_SIZE/2, DEFAULT_SVG_SIZE];

export const NUM_COORDINATES: { [key: number]: number[] } = {
  1: [DEFAULT_SVG_SIZE/2, 0, DEFAULT_SVG_SIZE, 0],
  2: [DEFAULT_SVG_SIZE/2, DEFAULT_SVG_SIZE/3, DEFAULT_SVG_SIZE, DEFAULT_SVG_SIZE/3],
  3: [DEFAULT_SVG_SIZE/2, 0, DEFAULT_SVG_SIZE, DEFAULT_SVG_SIZE/3],
  4: [DEFAULT_SVG_SIZE/2, DEFAULT_SVG_SIZE/3, DEFAULT_SVG_SIZE, 0],
  5: [DEFAULT_SVG_SIZE/2, DEFAULT_SVG_SIZE/3, DEFAULT_SVG_SIZE, 0, DEFAULT_SVG_SIZE/2, 0, DEFAULT_SVG_SIZE, 0],
  6: [DEFAULT_SVG_SIZE, DEFAULT_SVG_SIZE/3, DEFAULT_SVG_SIZE, 0],
  7: [DEFAULT_SVG_SIZE/2, 0, DEFAULT_SVG_SIZE, 0,DEFAULT_SVG_SIZE, DEFAULT_SVG_SIZE/3, DEFAULT_SVG_SIZE, 0],
  8: [DEFAULT_SVG_SIZE/2, DEFAULT_SVG_SIZE/3, DEFAULT_SVG_SIZE, DEFAULT_SVG_SIZE/3, DEFAULT_SVG_SIZE, DEFAULT_SVG_SIZE/3, DEFAULT_SVG_SIZE, 0],
  9: [DEFAULT_SVG_SIZE/2, DEFAULT_SVG_SIZE/3, DEFAULT_SVG_SIZE, DEFAULT_SVG_SIZE/3, DEFAULT_SVG_SIZE, DEFAULT_SVG_SIZE/3, DEFAULT_SVG_SIZE, 0, DEFAULT_SVG_SIZE/2, 0, DEFAULT_SVG_SIZE, 0],
}

export const CODE_VALIDATIONS = {
  label: "Enter a code",
  min: 1,
  max: 9999,
  errorText: "Value must be between 1 and 9999",
  requiredField: "Please provide a number"
}